/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed": "#40000e",
        "secondary-container": "#4a4949",
        "on-background": "#e2e2e2",
        "outline": "#ad8789",
        "on-secondary-container": "#bab8b7",
        "inverse-on-surface": "#2f3131",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#e7bcbe",
        "on-error": "#690005",
        "secondary": "#c9c6c5",
        "surface": "#121414",
        "tertiary": "#c8c6c5",
        "inverse-primary": "#be003a",
        "tertiary-fixed": "#e5e2e1",
        "surface-dim": "#121414",
        "inverse-surface": "#e2e2e2",
        "primary-container": "#ff506b",
        "surface-tint": "#ffb2b7",
        "on-surface": "#e2e2e2",
        "on-secondary-fixed-variant": "#474646",
        "tertiary-container": "#929090",
        "on-tertiary-fixed": "#1c1b1b",
        "primary-fixed": "#ffdadb",
        "on-primary-fixed-variant": "#91002b",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c9c6c5",
        "surface-container-high": "#282a2b",
        "on-tertiary-container": "#2a2a2a",
        "surface-variant": "#333535",
        "outline-variant": "#5d3f41",
        "surface-container-lowest": "#0c0f0f",
        "on-secondary": "#313030",
        "error": "#ffb4ab",
        "primary": "#ffb2b7",
        "background": "#121414",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container": "#1e2020",
        "surface-container-low": "#1a1c1c",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ffb2b7",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary-container": "#5b0017",
        "on-tertiary": "#313030",
        "on-primary": "#67001c",
        "surface-bright": "#38393a",
        "surface-container-highest": "#333535"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "80px",
        "container-max": "1280px",
        "stack-lg": "4rem",
        "gutter": "24px",
        "stack-md": "2rem",
        "margin-mobile": "20px",
        "stack-sm": "1rem"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-xl": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "display-lg-mobile": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
